# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BuildingCad
                                 A QGIS plugin
 This plugin can generate point features based on reference points and angles
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-01-12
        copyright            : (C) 2024 by Kalundborg Kommune
        email                : andj@kalundborg.dk
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load BuildingCad class from file BuildingCad.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .building_cad import BuildingCad
    return BuildingCad(iface)
